# local.kdl - the host's own half of the niri config - run through niri's own
# parser before it is allowed to become a file.
#
# nix/zde-config.nix already validates the assembled tree, but it assembles it
# with local.kdl empty, because it is shared by the flake package and every
# host and cannot know what any of them wrote. So the one file a person
# actually edits was the one file nothing checked. This is that check, and it
# lives here rather than in the flake's `checks` for the reason it has to: the
# text comes from `zde.niri.extraConfig` on a particular machine, so only the
# home-manager module evaluating that machine can hand it over. nix/home.nix
# sources local.kdl from this derivation, which is what puts it on the path of
# every `nixos-rebuild switch` rather than on the path of CI alone.
#
# What it buys is the difference between two failures. A config niri refuses is
# a *warning* to a running `niri --session`, not an error: it carries on with
# its compiled-in defaults, so the session comes up with none of zde's binds
# and niri's own terminal key spawning an alacritty this system does not
# install. A desktop where no key works and no key opens a terminal to find out
# why. A build that stops with the offending line printed is the same mistake,
# an hour earlier, with somebody still at a shell.
{
  runCommand,
  niri,
  zdeConfig,
  # The full text of local.kdl, generated by nix/home.nix from zde.niri.xkb and
  # zde.niri.extraConfig. Passed as a file rather than an environment variable:
  # it is arbitrary user text and there is no reason for a shell to ever see it.
  text,
}:
runCommand "zde-niri-local.kdl"
  {
    inherit text;
    passAsFile = [ "text" ];
    nativeBuildInputs = [ niri ];
  }
  ''
    # The same tree nix/zde-config.nix builds for its own check, with the one
    # difference that is the whole point: local.kdl is what this host wrote.
    # dynamic.kdl stays empty because that is its state on a first boot - zded
    # owns it, and nothing here can know what it will say later.
    mkdir check
    ln -s ${zdeConfig}/niri-config.kdl check/config.kdl
    ln -s ${zdeConfig}/binds.kdl check/binds.kdl
    cp "$textPath" check/local.kdl
    : > check/dynamic.kdl

    # niri names the file and the line, and the file it names is `local.kdl` -
    # which is a generated file nobody should edit. So the failure says where
    # the text came from and prints it numbered, because otherwise the fix is
    # to guess which line of a Nix string a KDL line number means.
    if ! niri validate -c check/config.kdl; then
      echo
      echo "The niri config this machine would install does not parse."
      echo
      echo "local.kdl is generated from zde.niri.xkb and zde.niri.extraConfig."
      echo "Those are what to edit - the line numbers above are lines of this:"
      echo
      cat -n check/local.kdl
      exit 1
    fi

    cp check/local.kdl "$out"
  ''
