package keymap

import (
	"strconv"
	"strings"
)

const header = "Generated by zde-keymap. Do not edit: the source is the keymap (common/keymap/keymap.yaml) and the registry beside it."

// EmitKDL renders the binds section of the niri config, in source order.
func EmitKDL(km *Keymap) string {
	var b strings.Builder
	b.WriteString("// " + header + "\n")
	b.WriteString("binds {\n")
	for _, bind := range km.Binds {
		b.WriteString("    " + bind.Key + bind.props() + " { " + bind.node() + "; }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// props renders the bind's niri properties. Only the ones that differ from
// niri's defaults are written, so the generated config stays readable.
func (b Bind) props() string {
	var p string
	if !b.Entry.Repeat {
		p += " repeat=false"
	}
	if b.Entry.WhenLocked {
		p += " allow-when-locked=true"
	}
	// niri's default is true, so this is the difference between a bind zde owns
	// and one the focused application can swallow by binding a Wayland global
	// nothing gates (registry.go, Unsuppressible).
	if b.Entry.Unsuppressible {
		p += " allow-inhibiting=false"
	}
	return p
}

func (b Bind) node() string {
	e := b.Entry
	if e.Native != "" {
		if b.Arg != "" {
			// Not Sprintf: niri action lines carry literal percent signs
			// (set-column-width "-10%"), so a format verb would either eat one
			// or leave %!(EXTRA) in the config.
			return strings.Replace(e.Native, argPlaceholder, b.Arg, 1)
		}
		return e.Native
	}
	argv := e.Spawn
	if b.Arg != "" {
		argv = append(argv[:len(argv):len(argv)], b.Arg)
	}
	quoted := make([]string, len(argv))
	for i, a := range argv {
		quoted[i] = strconv.Quote(a)
	}
	return "spawn " + strings.Join(quoted, " ")
}

// EmitCheatsheet renders the markdown cheatsheet, grouped like the action map.
func EmitCheatsheet(km *Keymap) string {
	var b strings.Builder
	b.WriteString("# zde keymap - Normal mode\n\n" + header + "\n")
	for _, g := range groups {
		first := true
		for _, bind := range km.Binds {
			if bind.Entry.Group != g {
				continue
			}
			if first {
				b.WriteString("\n## " + g + "\n\n| Key | Action | Does |\n|---|---|---|\n")
				first = false
			}
			desc := bind.Entry.Desc
			if bind.Arg != "" {
				desc += " " + bind.Arg
			}
			b.WriteString("| `" + bind.Key + "` | `" + bind.Action + "` | " + desc + " |\n")
		}
	}
	return b.String()
}

// EmitText renders the same cheatsheet as plain text, which is what `zde keys`
// prints.
//
// Two renderings of one list rather than one, because they are read in
// different places: the markdown is a document, and this is a terminal. Piping
// the markdown through a pager gives somebody a screen of pipes and backticks
// to read around; grepping it gives them a table row. Tab separated, key first,
// like every other list zde prints - so `zde keys | grep Mod+u` answers "what
// does that key do" in one line.
//
// A blank line and a bare group name between sections, and no other decoration:
// it goes through less, and it goes into a bug report.
func EmitText(km *Keymap) string {
	var b strings.Builder
	for _, g := range groups {
		first := true
		for _, bind := range km.Binds {
			if bind.Entry.Group != g {
				continue
			}
			if first {
				if b.Len() > 0 {
					b.WriteString("\n")
				}
				b.WriteString(g + "\n")
				first = false
			}
			desc := bind.Entry.Desc
			if bind.Arg != "" {
				desc += " " + bind.Arg
			}
			b.WriteString("  " + bind.Key + "\t" + bind.Action + "\t" + desc + "\n")
		}
	}
	return b.String()
}

// listed is one line of that file read back: one bind, as the build that
// generated the binds beside it wrote it down.
type listed struct{ key, action, desc string }

// parseText reads back what EmitText wrote. It lives beside the emitter
// deliberately: the format has one owner, and a reader in another file is how
// two halves of one format come to disagree about a tab.
// TestTheCheatsheetSurvivesBeingReadBack holds them together.
//
// A line it cannot read is dropped rather than refused. What is being read is a
// generated file and the reader is the palette: one unreadable line costs one
// row, and refusing the file costs every key on the machine.
func parseText(data []byte) []listed {
	var out []listed
	for _, line := range strings.Split(string(data), "\n") {
		// A group name sits on its own line, unindented, and the binds under it
		// are indented. Nothing else is in the file.
		if !strings.HasPrefix(line, "  ") {
			continue
		}
		parts := strings.Split(line[2:], "\t")
		if len(parts) != 3 {
			continue
		}
		out = append(out, listed{key: parts[0], action: parts[1], desc: parts[2]})
	}
	return out
}
