package keymap

import (
	"strconv"
	"strings"
)

const header = "Generated by zde-keymap. Do not edit: the source is the keymap (common/keymap/keymap.yaml) and the registry beside it."

// EmitKDL renders the binds section of the niri config, in source order.
func EmitKDL(km *Keymap) string {
	var b strings.Builder
	b.WriteString("// " + header + "\n")
	b.WriteString("binds {\n")
	for _, bind := range km.Binds {
		b.WriteString("    " + bind.Key + bind.props() + " { " + bind.node() + "; }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// props renders the bind's niri properties. Only the ones that differ from
// niri's defaults are written, so the generated config stays readable.
func (b Bind) props() string {
	var p string
	if !b.Entry.Repeat {
		p += " repeat=false"
	}
	if b.Entry.WhenLocked {
		p += " allow-when-locked=true"
	}
	return p
}

func (b Bind) node() string {
	e := b.Entry
	if e.Native != "" {
		if b.Arg != "" {
			// Not Sprintf: niri action lines carry literal percent signs
			// (set-column-width "-10%"), so a format verb would either eat one
			// or leave %!(EXTRA) in the config.
			return strings.Replace(e.Native, argPlaceholder, b.Arg, 1)
		}
		return e.Native
	}
	argv := e.Spawn
	if b.Arg != "" {
		argv = append(argv[:len(argv):len(argv)], b.Arg)
	}
	quoted := make([]string, len(argv))
	for i, a := range argv {
		quoted[i] = strconv.Quote(a)
	}
	return "spawn " + strings.Join(quoted, " ")
}

// EmitCheatsheet renders the markdown cheatsheet, grouped like the action map.
func EmitCheatsheet(km *Keymap) string {
	var b strings.Builder
	b.WriteString("# zde keymap - Normal mode\n\n" + header + "\n")
	for _, g := range groups {
		first := true
		for _, bind := range km.Binds {
			if bind.Entry.Group != g {
				continue
			}
			if first {
				b.WriteString("\n## " + g + "\n\n| Key | Action | Does |\n|---|---|---|\n")
				first = false
			}
			desc := bind.Entry.Desc
			if bind.Arg != "" {
				desc += " " + bind.Arg
			}
			// What the fingers do, not what niri hears: for a chord the input
			// daemon rewrites, those are different, and only one of them is
			// any use to somebody looking a key up.
			b.WriteString("| `" + bind.Pressed() + "` | `" + bind.Action + "` | " + desc + " |\n")
		}
	}
	return b.String()
}
